//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.28 at 03:07:12 PM CEST 
//


package pl.edu.pwr.classfinancemanager.soap.generateddata;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.edu.pwr.classfinancemanager.soap.generateddata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.edu.pwr.classfinancemanager.soap.generateddata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreatePaymentRequest }
     * 
     */
    public CreatePaymentRequest createCreatePaymentRequest() {
        return new CreatePaymentRequest();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link GetPersonsResponse }
     * 
     */
    public GetPersonsResponse createGetPersonsResponse() {
        return new GetPersonsResponse();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link GetInstalmentsByPersonRequest }
     * 
     */
    public GetInstalmentsByPersonRequest createGetInstalmentsByPersonRequest() {
        return new GetInstalmentsByPersonRequest();
    }

    /**
     * Create an instance of {@link GetEventsRequest }
     * 
     */
    public GetEventsRequest createGetEventsRequest() {
        return new GetEventsRequest();
    }

    /**
     * Create an instance of {@link GetPersonsRequest }
     * 
     */
    public GetPersonsRequest createGetPersonsRequest() {
        return new GetPersonsRequest();
    }

    /**
     * Create an instance of {@link GetInstalmentsRequest }
     * 
     */
    public GetInstalmentsRequest createGetInstalmentsRequest() {
        return new GetInstalmentsRequest();
    }

    /**
     * Create an instance of {@link GetPaymentsByPersonRequest }
     * 
     */
    public GetPaymentsByPersonRequest createGetPaymentsByPersonRequest() {
        return new GetPaymentsByPersonRequest();
    }

    /**
     * Create an instance of {@link GetInstalmentsResponse }
     * 
     */
    public GetInstalmentsResponse createGetInstalmentsResponse() {
        return new GetInstalmentsResponse();
    }

    /**
     * Create an instance of {@link Instalment }
     * 
     */
    public Instalment createInstalment() {
        return new Instalment();
    }

    /**
     * Create an instance of {@link GetPaymentsResponse }
     * 
     */
    public GetPaymentsResponse createGetPaymentsResponse() {
        return new GetPaymentsResponse();
    }

    /**
     * Create an instance of {@link GetPaymentsRequest }
     * 
     */
    public GetPaymentsRequest createGetPaymentsRequest() {
        return new GetPaymentsRequest();
    }

    /**
     * Create an instance of {@link CreateInstalmentRequest }
     * 
     */
    public CreateInstalmentRequest createCreateInstalmentRequest() {
        return new CreateInstalmentRequest();
    }

    /**
     * Create an instance of {@link CreateEventRequest }
     * 
     */
    public CreateEventRequest createCreateEventRequest() {
        return new CreateEventRequest();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link CreatePersonRequest }
     * 
     */
    public CreatePersonRequest createCreatePersonRequest() {
        return new CreatePersonRequest();
    }

    /**
     * Create an instance of {@link GetEventsResponse }
     * 
     */
    public GetEventsResponse createGetEventsResponse() {
        return new GetEventsResponse();
    }

}
